#!/bin/bash
# Author: Gero Niessen, 2013-02-15
# Description: Distributed Dependency Tracker Service
#
# Get function from functions library
. /etc/init.d/functions

SERVICENAME="Distributed Dependency Tracker Service"
DDTWAR=/home/ddt/DDT/Web/target/Web-1.0.war
SERVERPORT=9999
JETTYRUNNER=/home/ddt/jetty-runner-8.1.9.v20130131.jar
JAVA=/usr/bin/java
USER=ddt
LOG=/var/log/ddt.log

start() {
        #initlog -c "echo -n Starting $SERVICENAME: "
        /bin/rm $LOG
	/bin/touch $LOG
	/bin/chown $USER:$USER $LOG
	/bin/su - $USER -c "$JAVA -jar $JETTYRUNNER --port $SERVERPORT $DDTWAR > $LOG 2>&1 &"
        success $"$SERVICENAME startup"
        echo
}

stop() {
        #initlog -c "echo -n Stopping $SERVICENAME: "
        PID=$(/bin/ps ux -U $USER | /bin/grep $DDTWAR | /bin/grep $JAVA | /bin/awk '{ print $2 }')
        /bin/kill $PID
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status FOO
    ;;
    restart|reload|condrestart)
	stop
	start
    ;;
    *)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac
exit 0
