#!/bin/bash
#
# chkconfig: 35 90 12
# description: Distributed Dependency Tracker server
#
# Get function from functions library
. /etc/init.d/functions
# Start the service FOO
#java -jar jetty-runner-8.1.9.v20130131.jar --port 9999 --stop-port 9998 --stop-key ddt DDT/Web/target/Web-1.0.war 
SERVICENAME="Distributed Dependency Tracker Web Server"
DDTWAR=/home/ddt/DDT/Web/target/Web-1.0.war
SERVERPORT=9999
JETTYRUNNER=/home/ddt/jetty-runner-8.1.9.v20130131.jar
JAVA=/usr/bin/java
USER=ddt

start() {
        #initlog -c "echo -n Starting $SERVICENAME: "
        #RESULT=$("/bin/su - $USER -c \"$JAVA -jar $JETTYRUNNER --port $SERVERPORT $DDTWAR\" &")
	/bin/su - $USER -c "$JAVA -jar $JETTYRUNNER --port $SERVERPORT $DDTWAR &"
        ### Create the lock file ###
        #touch /var/lock/subsys/FOO
        success $"$SERVICENAME startup"
        echo
        }
# Restart the service FOO
stop() {
        #initlog -c "echo -n Stopping $SERVICENAME: "
        #PID=$(/bin/su - $USER -c /bin/ps ux | /bin/grep $DDTWAR | /bin/grep $JAVA | /bin/awk '{ print $2 }')
        PID=$(/bin/ps ux -U $USER | /bin/grep $DDTWAR | /bin/grep $JAVA | /bin/awk '{ print $2 }')
        /bin/kill $PID
        ### Now, delete the lock file ###
        #rm -f /var/lock/subsys/FOO
        #echo
        }
        ### main logic ###
case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    status)
        status FOO
    ;;
    restart|reload|condrestart)
	stop
	start
    ;;
    *)
    echo $"Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac
exit 0
